[project]
name = "frontend"
version = "0.1.0"
description = "CustomTkinter frontend for Pagyar Mosta Zrt."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=6.0.0",
    "httpx>=0.28.1",
]

[project.scripts]
frontend = "frontend:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
