"""init

Revision ID: f14eded8be6a
Revises: 
Create Date: 2026-10-04 22:57:43.638345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14eded8be6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('REGISTERED_CUSTOMER', 'UNREGISTERED_CUSTOMER', 'ADMIN', 'WAREHOUSE_STAFF', 'DELIVERY_MAN', name='user_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_capacity', sa.Float(), nullable=False),
    sa.Column('vehicle_plate_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('pickup_contact_id', sa.Integer(), nullable=False),
    sa.Column('delivery_contact_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_time_slot', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_time_slot', sa.String(length=50), nullable=True),
    sa.Column('current_status', sa.Enum('CREATED', 'READY_FOR_PICKUP', 'ASSIGNED_FOR_PICKUP', 'OUT_FOR_PICKUP', 'PICKED_UP', 'IN_WAREHOUSE', 'ASSIGNED_FOR_DELIVERY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED_DELIVERY', 'RETURNED_TO_SENDER', 'CANCELLED', name='package_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['pickup_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_tracking_id'), 'packages', ['tracking_id'], unique=True)
    op.create_table('package_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'READY_FOR_PICKUP', 'ASSIGNED_FOR_PICKUP', 'OUT_FOR_PICKUP', 'PICKED_UP', 'IN_WAREHOUSE', 'ASSIGNED_FOR_DELIVERY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED_DELIVERY', 'RETURNED_TO_SENDER', 'CANCELLED', name='package_status_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_events_courier_id'), 'package_events', ['courier_id'], unique=False)
    op.create_index(op.f('ix_package_events_package_id'), 'package_events', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_events_timestamp'), 'package_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_events_timestamp'), table_name='package_events')
    op.drop_index(op.f('ix_package_events_package_id'), table_name='package_events')
    op.drop_index(op.f('ix_package_events_courier_id'), table_name='package_events')
    op.drop_table('package_events')
    op.drop_index(op.f('ix_packages_tracking_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('couriers')
    op.drop_table('users')
    op.drop_table('contacts')
    # ### end Alembic commands ###
